name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      name: checkout
    - name: main
      shell: cmd
      run: |
        set PATH=C:\Miniconda3;C:\Miniconda3\Scripts;%USERPROFILE%\Miniconda3;%USERPROFILE%\Miniconda3\Scripts;%PATH%
        where pyfind || pip install mugicli
        mkdir listing
        pyfind C:\ -iname *.dll > listing\dlls.txt
        pyfind C:\ -iname *.exe > listing\exes.txt
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: listing
        path: listing
